--=================================Utility=================================
--Retry
UPDATE EXCEPTIONFRAGMENT SET ISMATCHED = FALSE where ISMATCHED = TRUE AND ANALYSISCOMPLETED = FALSE;
--Get unmatched exception
SELECT TOP 5 ID, TITLE, RCA, DATE, CONTEXT , DETAILMESSAGES   FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = TRUE AND F.ANALYSISCOMPLETED = FALSE AND F.IGNORE =FALSE;
--IGNORE
UPDATE EXCEPTIONFRAGMENT SET IGNORE = TRUE WHERE ID IN ();

--Analysize again.
UPDATE EXCEPTIONFRAGMENT SET ISMATCHED = FALSE WHERE ISMATCHED = TRUE AND ANALYSISCOMPLETED = FALSE;
--Reset(Debug)
UPDATE EXCEPTIONFRAGMENT SET ISMATCHED = FALSE, ANALYSISCOMPLETED = FALSE WHERE ISMATCHED = TRUE;

--=================================Summary=================================
--Total count
SELECT count(1) as TotalCount  FROM  EXCEPTIONFRAGMENT;
--Analysis Completed count
SELECT count(1) as CompletedCount  FROM  EXCEPTIONFRAGMENT F where F.ANALYSISCOMPLETED = TRUE;
--No templetes/ Not Matched count
SELECT count(1) NotMatchedCount  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = TRUE AND F.ANALYSISCOMPLETED = FALSE;
--To Be Analysized
SELECT count(1) ToBeAnalysized  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = FALSE AND F.ANALYSISCOMPLETED = FALSE;

--Summary(Total times).
SELECT T.TITLE, T.RCA, COUNT(*) AS TIMES from EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATE_EXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENT_ID
LEFT JOIN TEMPLETE AS T
ON R.TEMP_ID = T.ID
--WHERE F.DATE BETWEEN  '2013-04-01' AND '2013-04-30'
GROUP BY T.ID, T.TITLE, T.RCA
ORDER BY TIMES DESC;

--Summary(List).
SELECT T.TITLE, T.RCA, F.DATE from EXCEPTIONFRAGMENT AS F 
LEFT JOIN TEMPLATE_EXCEPTIONFRAGMENT AS R 
ON F.ID = R.FRAGMENT_ID
LEFT JOIN TEMPLETE AS T
ON R.TEMP_ID = T.ID
--WHERE F.DATE BETWEEN  '2013-04-01' AND '2013-04-30';
ORDER BY F.DATE DESC;

--Completed.
SELECT TITLE, RCA, DATE, ANALYSISCOMPLETED, ISMATCHED  FROM  EXCEPTIONFRAGMENT F where F.ANALYSISCOMPLETED = TRUE;
--No templetes/ Not Matched
SELECT TITLE, RCA, DATE, ANALYSISCOMPLETED, ISMATCHED  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = TRUE AND F.ANALYSISCOMPLETED = FALSE;
--Analysizing
SELECT TITLE, RCA, DATE, ANALYSISCOMPLETED, ISMATCHED  FROM  EXCEPTIONFRAGMENT F where F.ISMATCHED = FALSE AND F.ANALYSISCOMPLETED = FALSE;

